#!/usr/bin/env bash
set -eux

pip install .

# Copy configuration
settings_dir="$(jupyter --config-dir)"
mkdir --parents "${settings_dir}"

this_dir="$( dirname "${BASH_SOURCE[0]}" )"
cp -rT "${this_dir}/settings/.jupyter/" "${settings_dir}"
