name: Build package, run tests, and publish to PyPI

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  release:
    types:
      - published


jobs:
  dist:
    name: Build package
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - 3.9
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Build SDist & wheel
        # Installs `build` before invoking pyproject-build
        run: |
          pip install build wheel
          pyproject-build -ws
          
      - name: Check metadata
        run: twine check dist/*

      - uses: actions/upload-artifact@v2
        with:
          name: build
          path: dist/*
        
  checks:
    name: Check Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - 3.7
          - 3.8
          - 3.9
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - uses: actions/download-artifact@v2
        with:
          name: build
          path: dist

      - name: Install build + test dependencies
        run: pip install pytest dist/*.whl

      - name: Test package
        run: pytest

  publish:
    needs: [dist, checks]
    runs-on: ubuntu-latest
    if: github.event_name == 'release' && github.event.action == 'published'
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: build
          path: dist

      - uses: pypa/gh-action-pypi-publish@v1.4.2
        with:
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}
