name: Run tests
on:
  - push
  - pull_request

jobs:
  checks:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - 3.7
          - 3.8
          - 3.9
    name: Check Python ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}

      - name: Requirements check
        run: python -m pip list

      - name: Install package
        run: python -m pip install pytest .

      - name: Test package
        run: python -m pytest
